"""Add created_at to Order

Revision ID: 181718d96b69
Revises: 7c468929dc9c
Create Date: 2025-05-08 10:42:51.786382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '181718d96b69'
down_revision = '7c468929dc9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
