"""Initial migration with enhanced Order model

Revision ID: 28cac70e1b6a
Revises: 598acb5d35db
Create Date: 2025-06-19 01:22:36.528449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28cac70e1b6a'
down_revision = '598acb5d35db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_order')
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('province', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('district', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('sector', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('cell', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('village', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('address_details', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('payment_method', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('payment_status', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('order_status', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('order_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('shipped_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('delivered_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=500),
               existing_nullable=False)

    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_name', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('product_image', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.drop_column('product_image')
        batch_op.drop_column('product_name')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('address',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.drop_column('delivered_at')
        batch_op.drop_column('shipped_at')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('order_notes')
        batch_op.drop_column('order_status')
        batch_op.drop_column('payment_status')
        batch_op.drop_column('payment_method')
        batch_op.drop_column('address_details')
        batch_op.drop_column('village')
        batch_op.drop_column('cell')
        batch_op.drop_column('sector')
        batch_op.drop_column('district')
        batch_op.drop_column('province')
        batch_op.drop_column('phone')
        batch_op.drop_column('email')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    op.create_table('_alembic_tmp_order',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('customer_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('address', sa.VARCHAR(length=500), nullable=False),
    sa.Column('total_price', sa.FLOAT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('first_name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('email', sa.VARCHAR(length=150), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), nullable=False),
    sa.Column('province', sa.VARCHAR(length=50), nullable=False),
    sa.Column('district', sa.VARCHAR(length=50), nullable=False),
    sa.Column('sector', sa.VARCHAR(length=50), nullable=False),
    sa.Column('cell', sa.VARCHAR(length=50), nullable=True),
    sa.Column('village', sa.VARCHAR(length=50), nullable=True),
    sa.Column('address_details', sa.TEXT(), nullable=True),
    sa.Column('payment_method', sa.VARCHAR(length=50), nullable=False),
    sa.Column('payment_status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('order_status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('order_notes', sa.TEXT(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('shipped_at', sa.DATETIME(), nullable=True),
    sa.Column('delivered_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_user_order'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
