"""Add category_id as nullable

Revision ID: 3fb2a9f562e3
Revises: 938ffcc68609
Create Date: 2025-05-30 05:53:03.073090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fb2a9f562e3'
down_revision = '938ffcc68609'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_product')
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_product_category', 'category', ['category_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint('fk_product_category', type_='foreignkey')
        batch_op.drop_column('category_id')

    op.create_table('_alembic_tmp_product',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('price', sa.FLOAT(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('image', sa.VARCHAR(length=100), nullable=True),
    sa.Column('stock', sa.INTEGER(), nullable=True),
    sa.Column('category_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name='fk_product_category'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
