"""Add views column to Product

Revision ID: 409328dd38b5
Revises: ddb59c0598a1
Create Date: 2025-05-30 12:26:54.998330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '409328dd38b5'
down_revision = 'ddb59c0598a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('views', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('views')

    # ### end Alembic commands ###
