"""Add email columns to order table

Revision ID: 414d964ba0bd
Revises: b434ad7ccbbe
Create Date: 2025-06-19 00:48:31.565166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '414d964ba0bd'
down_revision = 'b434ad7ccbbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('province', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('district', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('sector', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('cell', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('village', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('address_details', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('payment_method', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('payment_status', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('order_status', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('order_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('shipped_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('delivered_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=500),
               existing_nullable=False)

    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_name', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('product_image', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.drop_column('product_image')
        batch_op.drop_column('product_name')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('address',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.drop_column('delivered_at')
        batch_op.drop_column('shipped_at')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('order_notes')
        batch_op.drop_column('order_status')
        batch_op.drop_column('payment_status')
        batch_op.drop_column('payment_method')
        batch_op.drop_column('address_details')
        batch_op.drop_column('village')
        batch_op.drop_column('cell')
        batch_op.drop_column('sector')
        batch_op.drop_column('district')
        batch_op.drop_column('province')
        batch_op.drop_column('phone')
        batch_op.drop_column('email')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
