"""Add additional fields to User

Revision ID: 490469f035b4
Revises: 3fb2a9f562e3
Create Date: 2025-05-30 06:55:25.835166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '490469f035b4'
down_revision = '3fb2a9f562e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lastname', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('NID', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('DOB', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('image', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('role', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('role')
        batch_op.drop_column('image')
        batch_op.drop_column('gender')
        batch_op.drop_column('DOB')
        batch_op.drop_column('NID')
        batch_op.drop_column('lastname')

    # ### end Alembic commands ###
