"""Add user_id to products table

Revision ID: 55456cb6a91e
Revises: 30071445ad8f
Create Date: 2025-06-26 09:15:26.763691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55456cb6a91e'
down_revision = '30071445ad8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_product_user', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint('fk_product_user', type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
