"""Initial migration with enhanced Order model

Revision ID: b33ce1e89c24
Revises: 54ec275c7653
Create Date: 2025-06-19 01:19:44.870565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b33ce1e89c24'
down_revision = '54ec275c7653'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(length=100), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('province', sa.String(length=50), nullable=False),
    sa.Column('district', sa.String(length=50), nullable=False),
    sa.Column('sector', sa.String(length=50), nullable=False),
    sa.Column('cell', sa.String(length=50), nullable=True),
    sa.Column('village', sa.String(length=50), nullable=True),
    sa.Column('address_details', sa.Text(), nullable=True),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('payment_status', sa.String(length=20), nullable=False),
    sa.Column('order_status', sa.String(length=20), nullable=False),
    sa.Column('order_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('shipped_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_user_order'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('order_status_history')
    op.drop_table('_alembic_tmp_order')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_alembic_tmp_order',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('customer_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('address', sa.VARCHAR(length=500), nullable=False),
    sa.Column('total_price', sa.FLOAT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('first_name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('email', sa.VARCHAR(length=150), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), nullable=False),
    sa.Column('province', sa.VARCHAR(length=50), nullable=False),
    sa.Column('district', sa.VARCHAR(length=50), nullable=False),
    sa.Column('sector', sa.VARCHAR(length=50), nullable=False),
    sa.Column('cell', sa.VARCHAR(length=50), nullable=True),
    sa.Column('village', sa.VARCHAR(length=50), nullable=True),
    sa.Column('address_details', sa.TEXT(), nullable=True),
    sa.Column('payment_method', sa.VARCHAR(length=50), nullable=False),
    sa.Column('payment_status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('order_status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('order_notes', sa.TEXT(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('shipped_at', sa.DATETIME(), nullable=True),
    sa.Column('delivered_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_user_order'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_status_history',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('order_id', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('order_table')
    # ### end Alembic commands ###
