"""Add address columns to user table

Revision ID: b434ad7ccbbe
Revises: 409328dd38b5
Create Date: 2025-06-18 23:15:01.100635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b434ad7ccbbe'
down_revision = '409328dd38b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('province', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('district', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('sector', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('cell', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('village', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('village')
        batch_op.drop_column('cell')
        batch_op.drop_column('sector')
        batch_op.drop_column('district')
        batch_op.drop_column('province')

    # ### end Alembic commands ###
