"""Add changes to Product

Revision ID: c4b46f65f01b
Revises: 490469f035b4
Create Date: 2025-05-30 07:20:02.810917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4b46f65f01b'
down_revision = '490469f035b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_order')
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_user_order', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_order', type_='foreignkey')
        batch_op.drop_column('user_id')

    op.create_table('_alembic_tmp_order',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('customer_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('address', sa.VARCHAR(length=200), nullable=False),
    sa.Column('total_price', sa.FLOAT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_user_order'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
