"""Add changes to Product

Revision ID: e8ae1110e1e3
Revises: c4b46f65f01b
Create Date: 2025-05-30 09:43:22.390641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8ae1110e1e3'
down_revision = 'c4b46f65f01b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=200), nullable=True))

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('slug')

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
